<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <AssemblyName>aisstream-net</AssemblyName>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <Title>AISStream.NET</Title>
        <PackageId>AISStream.NET</PackageId>
        <Authors>Albie Spriddell</Authors>
        <Description>A low-memory, high-performance library for receiving events from aisstream.io</Description>

        <PackageTags>aisstream websockets ais vessels positioning</PackageTags>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>

        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/aspriddell/aisstream-net</RepositoryUrl>
        <PackageProjectUrl>https://github.com/aspriddell/aisstream-net</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FastEnum" Version="2.0.5"/>
        <PackageReference Include="Riok.Mapperly" Version="4.2.1" PrivateAssets="all"/>
        <PackageReference Include="System.Text.Json" Version="9.0.8" />
    </ItemGroup>

</Project>
