name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Restore
        run: dotnet restore

      - name: Pack (Beta)
        run: dotnet pack -c Release -o . -p:PackageVersion=${{ github.event.release.tag_name }}-beta
        if: "github.event.release.prerelease"

      - name: Pack (Stable)
        run: dotnet pack -c Release -o . -p:PackageVersion=${{ github.event.release.tag_name }}
        if: "!github.event.release.prerelease"

      - name: Publish
        run: dotnet nuget push "*.nupkg" -k ${{ steps.login.outputs.NUGET_API_KEY }} --skip-duplicate -s https://api.nuget.org/v3/index.json
